"""Updated

Revision ID: 4977aba9798b
Revises: bf19af8dbfe3
Create Date: 2021-09-24 12:54:58.648097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4977aba9798b'
down_revision = 'bf19af8dbfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('province', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('vaccine_receipt', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('screen_question_2', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('screen_question_3', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('screen_question_4', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'completed')
    op.drop_column('customer', 'screen_question_4')
    op.drop_column('customer', 'screen_question_3')
    op.drop_column('customer', 'screen_question_2')
    op.drop_column('customer', 'vaccine_receipt')
    op.drop_column('customer', 'province')
    # ### end Alembic commands ###
