"""BusinessUSer

Revision ID: 63526a3c32ba
Revises: 4977aba9798b
Create Date: 2021-09-24 15:41:46.844880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63526a3c32ba'
down_revision = '4977aba9798b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_column('business', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('business', 'email')
    # ### end Alembic commands ###
