"""Initial migration.

Revision ID: bf19af8dbfe3
Revises: 
Create Date: 2021-09-24 10:59:45.463381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf19af8dbfe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('first_time_log', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'first_time_log')
    # ### end Alembic commands ###
